import type { Artist, Style } from "./types";

/**
 * Built-in demo data used when Supabase is not configured.
 * The same data lives in supabase/seed.sql for when you connect a database.
 */

export const DEMO_STYLES: Style[] = [
  {
    id: "s-bridal",
    name: "Bridal / Dulhan",
    slug: "bridal",
    description: "Full-hand dulhan mehandi — intricate jaal, portraits & storytelling designs.",
    image: "/art/style-bridal.svg",
    sortOrder: 1,
  },
  {
    id: "s-arabic",
    name: "Arabic",
    slug: "arabic",
    description: "Bold strokes, floral trails aur negative space — quick & classy.",
    image: "/art/style-arabic.svg",
    sortOrder: 2,
  },
  {
    id: "s-indo-arabic",
    name: "Indo-Arabic",
    slug: "indo-arabic",
    description: "Traditional jaal + Arabic boldness ka perfect mix.",
    image: "/art/style-indo-arabic.svg",
    sortOrder: 3,
  },
  {
    id: "s-traditional",
    name: "Traditional / Rajasthani",
    slug: "traditional",
    description: "Dense Marwari-Rajasthani work — peacocks, dulha-dulhan motifs.",
    image: "/art/style-traditional.svg",
    sortOrder: 4,
  },
  {
    id: "s-minimal",
    name: "Minimal / Modern",
    slug: "minimal",
    description: "Delicate strings, mandalas aur fingertips — less is more.",
    image: "/art/style-minimal.svg",
    sortOrder: 5,
  },
  {
    id: "s-festive",
    name: "Festive / Party",
    slug: "festive",
    description: "Karva Chauth, Teej, shaadi-guest looks — jaldi bhi, sundar bhi.",
    image: "/art/style-festive.svg",
    sortOrder: 6,
  },
];

function portfolio(n: number): string[] {
  return [1, 2, 3, 4].map((i) => `/art/artist-${n}-p${i}.svg`);
}

export const DEMO_ARTISTS: Artist[] = [
  {
    id: "a-01",
    userId: null,
    name: "Meera Rathore",
    slug: "meera-rathore",
    bio: "12 saal se bridal mehandi mein specialist. Rajasthani jaal aur dulha-dulhan portraits meri pehchaan hain — 800+ dulhanon ke haathon mein rang bhar chuki hoon. Organic henna, guaranteed dark stain.",
    city: "Jaipur",
    area: "Vaishali Nagar",
    whatsapp: "919876500001",
    experienceYears: 12,
    priceMin: 5100,
    priceMax: 21000,
    styles: ["bridal", "traditional", "indo-arabic"],
    profileImage: "/art/artist-1-profile.svg",
    portfolioImages: portfolio(1),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "a-02",
    userId: null,
    name: "Ayesha Khan",
    slug: "ayesha-khan",
    bio: "Arabic aur Indo-Arabic designs ki queen! Bold floral trails jo har photo mein pop karti hain. Engagement, Karva Chauth aur party bookings ke liye favourite. Home service available.",
    city: "Delhi",
    area: "Lajpat Nagar",
    whatsapp: "919876500002",
    experienceYears: 8,
    priceMin: 1100,
    priceMax: 11000,
    styles: ["arabic", "indo-arabic", "festive"],
    profileImage: "/art/artist-2-profile.svg",
    portfolioImages: portfolio(2),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "a-03",
    userId: null,
    name: "Prachi Deshmukh",
    slug: "prachi-deshmukh",
    bio: "Minimal & modern mehandi artist — delicate strings, geometric mandalas aur fingertip designs. Working brides aur modern shaadi looks ke liye perfect. Instagram par 50k+ followers.",
    city: "Pune",
    area: "Kothrud",
    whatsapp: "919876500003",
    experienceYears: 5,
    priceMin: 900,
    priceMax: 7500,
    styles: ["minimal", "arabic", "festive"],
    profileImage: "/art/artist-3-profile.svg",
    portfolioImages: portfolio(3),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "a-04",
    userId: null,
    name: "Farzana Shaikh",
    slug: "farzana-shaikh",
    bio: "Mumbai ki busy brides ka bharosa — 15 saal ka experience, film industry ke liye bhi kaam kiya hai. Bridal packages mein 2 assistants ke saath aati hoon taaki function time par khatam ho.",
    city: "Mumbai",
    area: "Bandra West",
    whatsapp: "919876500004",
    experienceYears: 15,
    priceMin: 7100,
    priceMax: 51000,
    styles: ["bridal", "indo-arabic", "arabic"],
    profileImage: "/art/artist-4-profile.svg",
    portfolioImages: portfolio(4),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-07T10:00:00Z",
  },
  {
    id: "a-05",
    userId: null,
    name: "Kiran Patel",
    slug: "kiran-patel",
    bio: "Ahmedabad mein traditional Gujarati aur Marwari mehandi ke liye jaani jaati hoon. Teej, Karva Chauth par group bookings ki special rates. Natural cones khud banati hoon.",
    city: "Ahmedabad",
    area: "Satellite",
    whatsapp: "919876500005",
    experienceYears: 10,
    priceMin: 700,
    priceMax: 15000,
    styles: ["traditional", "festive", "bridal"],
    profileImage: "/art/artist-5-profile.svg",
    portfolioImages: portfolio(5),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-09T10:00:00Z",
  },
  {
    id: "a-06",
    userId: null,
    name: "Sana Siddiqui",
    slug: "sana-siddiqui",
    bio: "Lucknow ki nafasat meri designs mein — chikankari se inspired jaali patterns sirf yahin milenge. Nawabi bridal look ke liye zaroor try karein.",
    city: "Lucknow",
    area: "Hazratganj",
    whatsapp: "919876500006",
    experienceYears: 7,
    priceMin: 1500,
    priceMax: 12000,
    styles: ["bridal", "traditional", "minimal"],
    profileImage: "/art/artist-6-profile.svg",
    portfolioImages: portfolio(6),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-11T10:00:00Z",
  },
  {
    id: "a-07",
    userId: null,
    name: "Divya Reddy",
    slug: "divya-reddy",
    bio: "Hyderabad mein South Indian + Arabic fusion mehandi. Pellikuthuru aur engagement ceremonies ki specialist. Bulk/group bookings welcome — sangeet mein 30+ guests tak handle kiye hain.",
    city: "Hyderabad",
    area: "Banjara Hills",
    whatsapp: "919876500007",
    experienceYears: 9,
    priceMin: 1100,
    priceMax: 18000,
    styles: ["arabic", "festive", "bridal"],
    profileImage: "/art/artist-7-profile.svg",
    portfolioImages: portfolio(7),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-13T10:00:00Z",
  },
  {
    id: "a-08",
    userId: null,
    name: "Ritu Agarwal",
    slug: "ritu-agarwal",
    bio: "Surat mein festive aur party mehandi ki go-to artist. Fast hands — 15 minute mein classy party design. Navratri aur shaadi season mein advance booking zaroori!",
    city: "Surat",
    area: "Adajan",
    whatsapp: "919876500008",
    experienceYears: 6,
    priceMin: 500,
    priceMax: 8000,
    styles: ["festive", "arabic", "minimal"],
    profileImage: "/art/artist-8-profile.svg",
    portfolioImages: portfolio(8),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-15T10:00:00Z",
  },
];
