import type { Category, Product } from "./types";

/**
 * Built-in catalogue used when Supabase is not configured (demo mode).
 * The same data lives in supabase/seed.sql for when you connect a database.
 */

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "c-coord",
    name: "Co-ord Sets",
    slug: "coord-sets",
    description: "Effortless matching sets — one look, zero styling stress.",
    image: "/products/cat-coord.svg",
    sortOrder: 1,
  },
  {
    id: "c-kurta-sets",
    name: "Kurta Sets",
    slug: "kurta-sets",
    description: "Kurti, pant & dupatta sets for every occasion.",
    image: "/products/cat-kurta-sets.svg",
    sortOrder: 2,
  },
  {
    id: "c-kurtis",
    name: "Kurtis",
    slug: "kurtis",
    description: "Everyday cotton kurtis you will live in.",
    image: "/products/cat-kurtis.svg",
    sortOrder: 3,
  },
  {
    id: "c-onepiece",
    name: "One Piece",
    slug: "one-piece",
    description: "Easy ethnic dresses — slip on and go.",
    image: "/products/cat-onepiece.svg",
    sortOrder: 4,
  },
  {
    id: "c-plus",
    name: "Plus Size",
    slug: "plus-size",
    description: "Beautiful fits in XL to 5XL. Style for every body.",
    image: "/products/cat-plus.svg",
    sortOrder: 5,
  },
  {
    id: "c-party",
    name: "Party Wear",
    slug: "party-wear",
    description: "Festive & party looks that turn heads.",
    image: "/products/cat-party.svg",
    sortOrder: 6,
  },
];

const SIZES_STD = ["S", "M", "L", "XL", "XXL"];
const SIZES_PLUS = ["XL", "XXL", "3XL", "4XL", "5XL"];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "p-01",
    name: "Gulaab Rani Co-ord Set",
    slug: "gulaab-rani-coord-set",
    description:
      "A rani-pink cotton co-ord with hand-block gulaab motifs. Relaxed straight kurta with matching flared pants — breathable mulmul lining keeps it airy all day.",
    price: 1499,
    compareAtPrice: 1999,
    categorySlug: "coord-sets",
    images: ["/products/p-01.svg"],
    sizes: SIZES_STD,
    fabric: "Pure Cotton",
    stock: 24,
    isNew: true,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-28T10:00:00Z",
  },
  {
    id: "p-02",
    name: "Neel Jaipur Co-ord Set",
    slug: "neel-jaipur-coord-set",
    description:
      "Indigo dabu-print co-ord set inspired by Jaipur's old city. Boxy shirt kurta with wide-leg pants; side pockets included, because obviously.",
    price: 1599,
    compareAtPrice: null,
    categorySlug: "coord-sets",
    images: ["/products/p-02.svg"],
    sizes: SIZES_STD,
    fabric: "Cotton Cambric",
    stock: 18,
    isNew: true,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-07-25T10:00:00Z",
  },
  {
    id: "p-03",
    name: "Kesar Bagh Co-ord Set",
    slug: "kesar-bagh-coord-set",
    description:
      "Saffron floral bagh print on soft flex cotton. Short kurta with gathered sharara-style pants — festive without trying too hard.",
    price: 1799,
    compareAtPrice: 2299,
    categorySlug: "coord-sets",
    images: ["/products/p-03.svg"],
    sizes: SIZES_STD,
    fabric: "Flex Cotton",
    stock: 12,
    isNew: false,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "p-04",
    name: "Chandni Anarkali Kurta Set",
    slug: "chandni-anarkali-kurta-set",
    description:
      "Moon-white anarkali with silver gota detailing, paired with churidar pants and a soft organza dupatta. Twirl-tested and approved.",
    price: 2199,
    compareAtPrice: 2799,
    categorySlug: "kurta-sets",
    images: ["/products/p-04.svg"],
    sizes: SIZES_STD,
    fabric: "Rayon Slub",
    stock: 15,
    isNew: true,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "p-05",
    name: "Mehendi Utsav Kurta Set",
    slug: "mehendi-utsav-kurta-set",
    description:
      "Mehendi-green straight kurta with mirror-work yoke, matching pants and a chiffon dupatta with tassel edges. Made for haldi-mehendi season.",
    price: 1899,
    compareAtPrice: 2499,
    categorySlug: "kurta-sets",
    images: ["/products/p-05.svg"],
    sizes: SIZES_STD,
    fabric: "Cotton Blend",
    stock: 20,
    isNew: false,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-15T10:00:00Z",
  },
  {
    id: "p-06",
    name: "Sindoori Chanderi Kurta Set",
    slug: "sindoori-chanderi-kurta-set",
    description:
      "Sindoori-red chanderi kurta with zari buttis, cotton-lined for comfort. Comes with straight pants and a matching chanderi dupatta.",
    price: 2499,
    compareAtPrice: 3199,
    categorySlug: "kurta-sets",
    images: ["/products/p-06.svg"],
    sizes: SIZES_STD,
    fabric: "Chanderi Silk",
    stock: 10,
    isNew: false,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-06-30T10:00:00Z",
  },
  {
    id: "p-07",
    name: "Ambar Daily Kurti",
    slug: "ambar-daily-kurti",
    description:
      "Sky-soft everyday kurti in breathable handloom cotton with wooden buttons and side slits. The one you will reach for every Monday.",
    price: 749,
    compareAtPrice: 999,
    categorySlug: "kurtis",
    images: ["/products/p-07.svg"],
    sizes: SIZES_STD,
    fabric: "Handloom Cotton",
    stock: 40,
    isNew: false,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "p-08",
    name: "Dhoop Chhaon Kurti",
    slug: "dhoop-chhaon-kurti",
    description:
      "Ombre sunset kurti in mul cotton — dhoop fading into chhaon. A-line cut with princess seams and deep pockets.",
    price: 849,
    compareAtPrice: null,
    categorySlug: "kurtis",
    images: ["/products/p-08.svg"],
    sizes: SIZES_STD,
    fabric: "Mul Cotton",
    stock: 35,
    isNew: true,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-08-03T10:00:00Z",
  },
  {
    id: "p-09",
    name: "Titli Angrakha Kurti",
    slug: "titli-angrakha-kurti",
    description:
      "Angrakha-style wrap kurti with butterfly-block print and dori tie-up. Flattering overlap silhouette in soft cambric.",
    price: 899,
    compareAtPrice: 1199,
    categorySlug: "kurtis",
    images: ["/products/p-09.svg"],
    sizes: SIZES_STD,
    fabric: "Cotton Cambric",
    stock: 28,
    isNew: false,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-06-20T10:00:00Z",
  },
  {
    id: "p-10",
    name: "Baarish Midi Dress",
    slug: "baarish-midi-dress",
    description:
      "Monsoon-blue tiered midi dress in crinkle cotton with smocked bodice and balloon sleeves. Ethnic at heart, easy everywhere.",
    price: 1299,
    compareAtPrice: 1699,
    categorySlug: "one-piece",
    images: ["/products/p-10.svg"],
    sizes: SIZES_STD,
    fabric: "Crinkle Cotton",
    stock: 22,
    isNew: true,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "p-11",
    name: "Genda Phool Maxi",
    slug: "genda-phool-maxi",
    description:
      "Marigold-yellow maxi dress with genda phool print, shirred back and flowy gathers. Sunshine, stitched.",
    price: 1399,
    compareAtPrice: null,
    categorySlug: "one-piece",
    images: ["/products/p-11.svg"],
    sizes: SIZES_STD,
    fabric: "Rayon",
    stock: 16,
    isNew: false,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-18T10:00:00Z",
  },
  {
    id: "p-12",
    name: "Raat Rani Curve Kurta Set",
    slug: "raat-rani-curve-kurta-set",
    description:
      "Midnight-purple kurta set designed for curves — princess panels, longer length, roomy hips. With pants and dupatta, XL to 5XL.",
    price: 1999,
    compareAtPrice: 2599,
    categorySlug: "plus-size",
    images: ["/products/p-12.svg"],
    sizes: SIZES_PLUS,
    fabric: "Rayon Slub",
    stock: 25,
    isNew: true,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-08-02T10:00:00Z",
  },
  {
    id: "p-13",
    name: "Gulmohar Curve Kurti",
    slug: "gulmohar-curve-kurti",
    description:
      "Gulmohar-red A-line kurti cut generously through the bust and hip, with side slits that actually sit right. XL to 5XL.",
    price: 949,
    compareAtPrice: 1249,
    categorySlug: "plus-size",
    images: ["/products/p-13.svg"],
    sizes: SIZES_PLUS,
    fabric: "Pure Cotton",
    stock: 30,
    isNew: false,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "p-14",
    name: "Noor Curve Co-ord Set",
    slug: "noor-curve-coord-set",
    description:
      "Pearl-grey co-ord with silver foil buttis, tailored for plus sizes with an elasticated back and wide-leg pants. XL to 5XL.",
    price: 1699,
    compareAtPrice: null,
    categorySlug: "plus-size",
    images: ["/products/p-14.svg"],
    sizes: SIZES_PLUS,
    fabric: "Cotton Blend",
    stock: 14,
    isNew: false,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-06-25T10:00:00Z",
  },
  {
    id: "p-15",
    name: "Jashn Velvet Kurta Set",
    slug: "jashn-velvet-kurta-set",
    description:
      "Emerald velvet kurta with zardozi neckline, silk-touch pants and a net dupatta with sequin edging. Shaadi-season heavy hitter.",
    price: 2999,
    compareAtPrice: 3999,
    categorySlug: "party-wear",
    images: ["/products/p-15.svg"],
    sizes: SIZES_STD,
    fabric: "Micro Velvet",
    stock: 8,
    isNew: true,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-08-04T10:00:00Z",
  },
  {
    id: "p-16",
    name: "Sitara Sharara Set",
    slug: "sitara-sharara-set",
    description:
      "Star-embroidered short kurti with flared sharara and shimmer dupatta. Georgette with full lining — dance-floor certified.",
    price: 2699,
    compareAtPrice: 3499,
    categorySlug: "party-wear",
    images: ["/products/p-16.svg"],
    sizes: SIZES_STD,
    fabric: "Georgette",
    stock: 11,
    isNew: false,
    isBestseller: true,
    isActive: true,
    createdAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "p-17",
    name: "Mor Pankh Lehenga Set",
    slug: "mor-pankh-lehenga-set",
    description:
      "Peacock-teal flared lehenga with gota lace, matching blouse and a soft net dupatta. Light enough to actually enjoy the function.",
    price: 3499,
    compareAtPrice: 4499,
    categorySlug: "party-wear",
    images: ["/products/p-17.svg"],
    sizes: SIZES_STD,
    fabric: "Silk Blend",
    stock: 6,
    isNew: false,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "p-18",
    name: "Shaam Chikankari Kurti",
    slug: "shaam-chikankari-kurti",
    description:
      "Dusk-mauve georgette kurti with hand chikankari jaal and sequin highlights. Comes with a cotton slip. Evening-ready elegance.",
    price: 1599,
    compareAtPrice: 1999,
    categorySlug: "party-wear",
    images: ["/products/p-18.svg"],
    sizes: SIZES_STD,
    fabric: "Georgette",
    stock: 19,
    isNew: true,
    isBestseller: false,
    isActive: true,
    createdAt: "2026-08-06T10:00:00Z",
  },
];
