import type { Artist, Style } from "./types";

/**
 * Built-in demo data used when Supabase is not configured.
 * The same data lives in supabase/seed.sql for when you connect a database.
 */

export const DEMO_STYLES: Style[] = [
  {
    id: "s-bridal",
    name: "Bridal / Dulhan",
    slug: "bridal",
    description: "Full-hand bridal mehandi — intricate jaal patterns, portraits & storytelling designs.",
    image: "/art/style-bridal.jpg",
    sortOrder: 1,
  },
  {
    id: "s-arabic",
    name: "Arabic",
    slug: "arabic",
    description: "Bold strokes, floral trails and negative space — quick & classy.",
    image: "/art/style-arabic.jpg",
    sortOrder: 2,
  },
  {
    id: "s-indo-arabic",
    name: "Indo-Arabic",
    slug: "indo-arabic",
    description: "The perfect blend of traditional jaal and bold Arabic strokes.",
    image: "/art/style-indo-arabic.jpg",
    sortOrder: 3,
  },
  {
    id: "s-traditional",
    name: "Traditional / Rajasthani",
    slug: "traditional",
    description: "Dense Marwari-Rajasthani work — peacocks and bride-and-groom motifs.",
    image: "/art/style-traditional.jpg",
    sortOrder: 4,
  },
  {
    id: "s-minimal",
    name: "Minimal / Modern",
    slug: "minimal",
    description: "Delicate strings, mandalas and fingertip details — less is more.",
    image: "/art/style-minimal.jpg",
    sortOrder: 5,
  },
  {
    id: "s-festive",
    name: "Festive / Party",
    slug: "festive",
    description: "Karva Chauth, Teej and wedding-guest looks — quick to apply, beautiful to wear.",
    image: "/art/style-festive.jpg",
    sortOrder: 6,
  },
];

function portfolio(n: number): string[] {
  return [1, 2, 3, 4].map((i) => `/art/artist-${n}-p${i}.jpg`);
}

/** Demo-only payment details (clearly fake; real ones are uploaded by users). */
const demoUpi = (handle: string) => ({
  upiId: `${handle}@demoupi`,
  upiQr: "/art/qr-demo.svg",
});

export const DEMO_ARTISTS: Artist[] = [
  {
    id: "a-01",
    userId: null,
    name: "Meera Rathore",
    slug: "meera-rathore",
    bio: "Bridal mehandi specialist for 12 years. Rajasthani jaal and bride-and-groom portraits are my signature — I have adorned the hands of 800+ brides. Organic henna, guaranteed dark stain.",
    city: "Jaipur",
    area: "Vaishali Nagar",
    whatsapp: "919876500001",
    experienceYears: 12,
    priceMin: 5100,
    priceMax: 21000,
    styles: ["bridal", "traditional", "indo-arabic"],
    profileImage: "/art/artist-1-profile.jpg",
    portfolioImages: portfolio(1),
    ...demoUpi("meera"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "a-02",
    userId: null,
    name: "Ayesha Khan",
    slug: "ayesha-khan",
    bio: "The queen of Arabic and Indo-Arabic designs! Bold floral trails that pop in every photo. A favourite for engagement, Karva Chauth and party bookings. Home service available.",
    city: "Delhi",
    area: "Lajpat Nagar",
    whatsapp: "919876500002",
    experienceYears: 8,
    priceMin: 1100,
    priceMax: 11000,
    styles: ["arabic", "indo-arabic", "festive"],
    profileImage: "/art/artist-2-profile.jpg",
    portfolioImages: portfolio(2),
    ...demoUpi("ayesha"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "a-03",
    userId: null,
    name: "Prachi Deshmukh",
    slug: "prachi-deshmukh",
    bio: "Minimal & modern mehandi artist — delicate strings, geometric mandalas and fingertip designs. Perfect for working brides and modern wedding looks. 50k+ followers on Instagram.",
    city: "Pune",
    area: "Kothrud",
    whatsapp: "919876500003",
    experienceYears: 5,
    priceMin: 900,
    priceMax: 7500,
    styles: ["minimal", "arabic", "festive"],
    profileImage: "/art/artist-3-profile.jpg",
    portfolioImages: portfolio(3),
    ...demoUpi("prachi"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "a-04",
    userId: null,
    name: "Farzana Shaikh",
    slug: "farzana-shaikh",
    bio: "Trusted by Mumbai's busiest brides — 15 years of experience, including work for the film industry. My bridal packages include 2 assistants so everything is finished in time for the function.",
    city: "Mumbai",
    area: "Bandra West",
    whatsapp: "919876500004",
    experienceYears: 15,
    priceMin: 7100,
    priceMax: 51000,
    styles: ["bridal", "indo-arabic", "arabic"],
    profileImage: "/art/artist-4-profile.jpg",
    portfolioImages: portfolio(4),
    ...demoUpi("farzana"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-07T10:00:00Z",
  },
  {
    id: "a-05",
    userId: null,
    name: "Kiran Patel",
    slug: "kiran-patel",
    bio: "Known across Ahmedabad for traditional Gujarati and Marwari mehandi. Special rates for group bookings on Teej and Karva Chauth. I make my own natural henna cones.",
    city: "Ahmedabad",
    area: "Satellite",
    whatsapp: "919876500005",
    experienceYears: 10,
    priceMin: 700,
    priceMax: 15000,
    styles: ["traditional", "festive", "bridal"],
    profileImage: "/art/artist-5-profile.jpg",
    portfolioImages: portfolio(5),
    ...demoUpi("kiran"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-09T10:00:00Z",
  },
  {
    id: "a-06",
    userId: null,
    name: "Sana Siddiqui",
    slug: "sana-siddiqui",
    bio: "The refinement of Lucknow lives in my designs — chikankari-inspired jaali patterns you won't find anywhere else. A must-try for the regal Nawabi bridal look.",
    city: "Lucknow",
    area: "Hazratganj",
    whatsapp: "919876500006",
    experienceYears: 7,
    priceMin: 1500,
    priceMax: 12000,
    styles: ["bridal", "traditional", "minimal"],
    profileImage: "/art/artist-6-profile.jpg",
    portfolioImages: portfolio(6),
    ...demoUpi("sana"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-11T10:00:00Z",
  },
  {
    id: "a-07",
    userId: null,
    name: "Divya Reddy",
    slug: "divya-reddy",
    bio: "South Indian + Arabic fusion mehandi in Hyderabad. Specialist in Pellikuthuru and engagement ceremonies. Bulk/group bookings welcome — I have handled 30+ guests at a single sangeet.",
    city: "Hyderabad",
    area: "Banjara Hills",
    whatsapp: "919876500007",
    experienceYears: 9,
    priceMin: 1100,
    priceMax: 18000,
    styles: ["arabic", "festive", "bridal"],
    profileImage: "/art/artist-7-profile.jpg",
    portfolioImages: portfolio(7),
    ...demoUpi("divya"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-13T10:00:00Z",
  },
  {
    id: "a-08",
    userId: null,
    name: "Ritu Agarwal",
    slug: "ritu-agarwal",
    bio: "Surat's go-to artist for festive and party mehandi. Fast hands — a classy party design in just 15 minutes. Advance booking is a must during Navratri and the wedding season!",
    city: "Surat",
    area: "Adajan",
    whatsapp: "919876500008",
    experienceYears: 6,
    priceMin: 500,
    priceMax: 8000,
    styles: ["festive", "arabic", "minimal"],
    profileImage: "/art/artist-8-profile.jpg",
    portfolioImages: portfolio(8),
    ...demoUpi("ritu"),
    isApproved: true,
    isActive: true,
    createdAt: "2026-07-15T10:00:00Z",
  },
];
