-- ============================================================
-- OPTIONAL: 8 sample artists for testing/preview only.
-- Production mein mat chalao — real artists /join se register
-- karengi ya admin panel se add hongi.
-- Baad mein hatane ke liye:  delete from public.artists;
-- ============================================================

insert into public.artists
  (name, slug, bio, city, area, whatsapp, experience_years, price_min, price_max, styles, profile_image, portfolio_images, is_approved, is_active)
values
  ('Meera Rathore', 'meera-rathore', '12 saal se bridal mehandi mein specialist. Rajasthani jaal aur dulha-dulhan portraits meri pehchaan hain — 800+ dulhanon ke haathon mein rang bhar chuki hoon. Organic henna, guaranteed dark stain.', 'Jaipur', 'Vaishali Nagar', '919876500001', 12, 5100, 21000, '{"bridal","traditional","indo-arabic"}', '/art/artist-1-profile.svg', '{"/art/artist-1-p1.svg","/art/artist-1-p2.svg","/art/artist-1-p3.svg","/art/artist-1-p4.svg"}', true, true),
  ('Ayesha Khan', 'ayesha-khan', 'Arabic aur Indo-Arabic designs ki queen! Bold floral trails jo har photo mein pop karti hain. Engagement, Karva Chauth aur party bookings ke liye favourite. Home service available.', 'Delhi', 'Lajpat Nagar', '919876500002', 8, 1100, 11000, '{"arabic","indo-arabic","festive"}', '/art/artist-2-profile.svg', '{"/art/artist-2-p1.svg","/art/artist-2-p2.svg","/art/artist-2-p3.svg","/art/artist-2-p4.svg"}', true, true),
  ('Prachi Deshmukh', 'prachi-deshmukh', 'Minimal & modern mehandi artist — delicate strings, geometric mandalas aur fingertip designs. Working brides aur modern shaadi looks ke liye perfect. Instagram par 50k+ followers.', 'Pune', 'Kothrud', '919876500003', 5, 900, 7500, '{"minimal","arabic","festive"}', '/art/artist-3-profile.svg', '{"/art/artist-3-p1.svg","/art/artist-3-p2.svg","/art/artist-3-p3.svg","/art/artist-3-p4.svg"}', true, true),
  ('Farzana Shaikh', 'farzana-shaikh', 'Mumbai ki busy brides ka bharosa — 15 saal ka experience, film industry ke liye bhi kaam kiya hai. Bridal packages mein 2 assistants ke saath aati hoon taaki function time par khatam ho.', 'Mumbai', 'Bandra West', '919876500004', 15, 7100, 51000, '{"bridal","indo-arabic","arabic"}', '/art/artist-4-profile.svg', '{"/art/artist-4-p1.svg","/art/artist-4-p2.svg","/art/artist-4-p3.svg","/art/artist-4-p4.svg"}', true, true),
  ('Kiran Patel', 'kiran-patel', 'Ahmedabad mein traditional Gujarati aur Marwari mehandi ke liye jaani jaati hoon. Teej, Karva Chauth par group bookings ki special rates. Natural cones khud banati hoon.', 'Ahmedabad', 'Satellite', '919876500005', 10, 700, 15000, '{"traditional","festive","bridal"}', '/art/artist-5-profile.svg', '{"/art/artist-5-p1.svg","/art/artist-5-p2.svg","/art/artist-5-p3.svg","/art/artist-5-p4.svg"}', true, true),
  ('Sana Siddiqui', 'sana-siddiqui', 'Lucknow ki nafasat meri designs mein — chikankari se inspired jaali patterns sirf yahin milenge. Nawabi bridal look ke liye zaroor try karein.', 'Lucknow', 'Hazratganj', '919876500006', 7, 1500, 12000, '{"bridal","traditional","minimal"}', '/art/artist-6-profile.svg', '{"/art/artist-6-p1.svg","/art/artist-6-p2.svg","/art/artist-6-p3.svg","/art/artist-6-p4.svg"}', true, true),
  ('Divya Reddy', 'divya-reddy', 'Hyderabad mein South Indian + Arabic fusion mehandi. Pellikuthuru aur engagement ceremonies ki specialist. Bulk/group bookings welcome — sangeet mein 30+ guests tak handle kiye hain.', 'Hyderabad', 'Banjara Hills', '919876500007', 9, 1100, 18000, '{"arabic","festive","bridal"}', '/art/artist-7-profile.svg', '{"/art/artist-7-p1.svg","/art/artist-7-p2.svg","/art/artist-7-p3.svg","/art/artist-7-p4.svg"}', true, true),
  ('Ritu Agarwal', 'ritu-agarwal', 'Surat mein festive aur party mehandi ki go-to artist. Fast hands — 15 minute mein classy party design. Navratri aur shaadi season mein advance booking zaroori!', 'Surat', 'Adajan', '919876500008', 6, 500, 8000, '{"festive","arabic","minimal"}', '/art/artist-8-profile.svg', '{"/art/artist-8-p1.svg","/art/artist-8-p2.svg","/art/artist-8-p3.svg","/art/artist-8-p4.svg"}', true, true)
on conflict (slug) do nothing;
