-- ============================================================
-- OPTIONAL: 8 sample artists for testing/preview only.
-- Do not run this in production — real artists register via
-- /join or are added from the admin panel.
-- To remove them later:  delete from public.artists;
-- ============================================================

insert into public.artists
  (name, slug, bio, city, area, whatsapp, experience_years, price_min, price_max, styles, profile_image, portfolio_images, is_approved, is_active)
values
  ('Meera Rathore', 'meera-rathore', 'Bridal mehandi specialist for 12 years. Rajasthani jaal and bride-and-groom portraits are my signature — I have adorned the hands of 800+ brides. Organic henna, guaranteed dark stain.', 'Jaipur', 'Vaishali Nagar', '919876500001', 12, 5100, 21000, '{"bridal","traditional","indo-arabic"}', '/art/artist-1-profile.jpg', '{"/art/artist-1-p1.jpg","/art/artist-1-p2.jpg","/art/artist-1-p3.jpg","/art/artist-1-p4.jpg"}', true, true),
  ('Ayesha Khan', 'ayesha-khan', 'The queen of Arabic and Indo-Arabic designs! Bold floral trails that pop in every photo. A favourite for engagement, Karva Chauth and party bookings. Home service available.', 'Delhi', 'Lajpat Nagar', '919876500002', 8, 1100, 11000, '{"arabic","indo-arabic","festive"}', '/art/artist-2-profile.jpg', '{"/art/artist-2-p1.jpg","/art/artist-2-p2.jpg","/art/artist-2-p3.jpg","/art/artist-2-p4.jpg"}', true, true),
  ('Prachi Deshmukh', 'prachi-deshmukh', 'Minimal & modern mehandi artist — delicate strings, geometric mandalas and fingertip designs. Perfect for working brides and modern wedding looks. 50k+ followers on Instagram.', 'Pune', 'Kothrud', '919876500003', 5, 900, 7500, '{"minimal","arabic","festive"}', '/art/artist-3-profile.jpg', '{"/art/artist-3-p1.jpg","/art/artist-3-p2.jpg","/art/artist-3-p3.jpg","/art/artist-3-p4.jpg"}', true, true),
  ('Farzana Shaikh', 'farzana-shaikh', 'Trusted by Mumbai''s busiest brides — 15 years of experience, including work for the film industry. My bridal packages include 2 assistants so everything is finished in time for the function.', 'Mumbai', 'Bandra West', '919876500004', 15, 7100, 51000, '{"bridal","indo-arabic","arabic"}', '/art/artist-4-profile.jpg', '{"/art/artist-4-p1.jpg","/art/artist-4-p2.jpg","/art/artist-4-p3.jpg","/art/artist-4-p4.jpg"}', true, true),
  ('Kiran Patel', 'kiran-patel', 'Known across Ahmedabad for traditional Gujarati and Marwari mehandi. Special rates for group bookings on Teej and Karva Chauth. I make my own natural henna cones.', 'Ahmedabad', 'Satellite', '919876500005', 10, 700, 15000, '{"traditional","festive","bridal"}', '/art/artist-5-profile.jpg', '{"/art/artist-5-p1.jpg","/art/artist-5-p2.jpg","/art/artist-5-p3.jpg","/art/artist-5-p4.jpg"}', true, true),
  ('Sana Siddiqui', 'sana-siddiqui', 'The refinement of Lucknow lives in my designs — chikankari-inspired jaali patterns you won''t find anywhere else. A must-try for the regal Nawabi bridal look.', 'Lucknow', 'Hazratganj', '919876500006', 7, 1500, 12000, '{"bridal","traditional","minimal"}', '/art/artist-6-profile.jpg', '{"/art/artist-6-p1.jpg","/art/artist-6-p2.jpg","/art/artist-6-p3.jpg","/art/artist-6-p4.jpg"}', true, true),
  ('Divya Reddy', 'divya-reddy', 'South Indian + Arabic fusion mehandi in Hyderabad. Specialist in Pellikuthuru and engagement ceremonies. Bulk/group bookings welcome — I have handled 30+ guests at a single sangeet.', 'Hyderabad', 'Banjara Hills', '919876500007', 9, 1100, 18000, '{"arabic","festive","bridal"}', '/art/artist-7-profile.jpg', '{"/art/artist-7-p1.jpg","/art/artist-7-p2.jpg","/art/artist-7-p3.jpg","/art/artist-7-p4.jpg"}', true, true),
  ('Ritu Agarwal', 'ritu-agarwal', 'Surat''s go-to artist for festive and party mehandi. Fast hands — a classy party design in just 15 minutes. Advance booking is a must during Navratri and the wedding season!', 'Surat', 'Adajan', '919876500008', 6, 500, 8000, '{"festive","arabic","minimal"}', '/art/artist-8-profile.jpg', '{"/art/artist-8-profile.jpg"}', true, true)
on conflict (slug) do nothing;
